dataset:
  name: nuscenes-lidarseg
  root: /home/nfs_data/yangshang19/smr/torchsparse-data/benchmarks/nuscenes
  max_saver: 'mIoU'
  version: 'v1.0-trainval'
  max_sweeps: 1
  max_points: 60000
  num_classes: 32

model:
  name: minkunet
  in_channels: 6
  cr: 1.0
  # tag: ['whole', 'whole', 'whole', 
  #       'whole', 'whole', 
  #       'whole', 'whole', 
  #       'whole', 'whole', 'end']
  # tag: ['simple', 'simple', 'simple', 
  #       'simple', 'simple', 
  #       'simple', 'simple', 
  #       'simple', 'simple', 'end']
  # tag: ['whole', 'whole', 'whole', 
  #       'whole', 'whole', 
  #       'whole', 'whole', 
  #       'whole', 'whole', 'end']

