dataset:
  train_max_points: 60000
  val_max_points: 60000


model:
  name: second
  box_code_cfg: 
    code_size: 9
    encode_angle_by_sincos: True
  in_channels: 5
  voxelization_cfg:
    voxel_size: [0.1, 0.2, 0.1]
    max_number_of_voxels: [60000, 60000]
    max_points_per_voxel: 10
  proposal_stage: 3
  negative_anchor_threshold: [0.45, 0.4, 0.35, 0.4, 0.35, 0.4, 0.3, 0.35, 0.4, 0.4]
  positive_anchor_threshold: [0.6, 0.55, 0.5, 0.55, 0.5, 0.55, 0.5, 0.5, 0.6, 0.6]
  use_multihead: True
  use_direction_classifier: False
  cls_weight: 1.0
  reg_weight: 0.25
  dir_weight: 0.2
  pos_cls_weight: 1.0
  neg_cls_weight: 2.0
  dir_offset: 0.785398
  dir_limit_offset: 0.0
  num_dir_bins: 2
  last_kernel_size: 3
  reg_config:
    shared_channels: 64
    num_middle_layers: 1
    mid_channels: 64
    reg_list:
      reg: 2
      height: 1
      size: 3
      angle: 2
      velo: 2
  rpn_head_configs: [
      {
          'head_cls_name': ['car']
      },
      {
          'head_cls_name': ['truck', 'construction_vehicle']
      },
      {
          'head_cls_name': ['bus', 'trailer']
      },
      {
          'head_cls_name': ['barrier']
      },
      {
          'head_cls_name': ['motorcycle', 'bicycle']
      },
      {
          'head_cls_name': ['pedestrian', 'traffic_cone']
      }
  ]
  backbone_2d_configs: 
    num_channels: [128, 256]
    layer_nums: [5, 5]
    stride: [1, 2]
    up_num_channels: [256, 256]
    up_stride: [1, 2]
  
  loss_cfg:
    beta: 0.1111111111111111
    code_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.2, 0.2]    

  nms_configs:
    roi_threshold: 0.1
    nms_threshold: 0.2
    joint_nms: False
    before_nms_max: 1000
    after_nms_max: 83
  
  regress_ignored_anchors: False

num_epochs: 20
batch_size: 32

criterion:
  name: sigmoid-focal
  gamma: 2.0
  alpha: 0.25

optimizer:
  name: adam_onecycle
  lr: 0.003
  weight_decay: 0.01

scheduler:
  name: onecycle
  momentums: [0.95, 0.85]
  div_factor: 10
  pct_start: 0.4
