workers_per_gpu: 1
evaluation_frequency: 1

resnet_tag: ['whole', 
       'whole', 'whole', 
       'whole', 'whole', 
       'whole', 'whole', 'whole', 
       'end']

unet_tag: ['whole', 'whole', 'whole', 
        'whole', 'whole', 
        'whole', 'whole', 
        'whole', 'whole', 'end']

